# Site settings
title: Stepan Kuzmin
author: Stepan Kuzmin
email: to.stepan.kuzmin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sperical Mercator in vacuum
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://stepankuzmin.ru' # the base hostname & protocol for your site
twitter_username: stepankuzmin
github_username:  stepankuzmin

# Build settings
permalink: /all/:title
markdown: kramdown
exclude: ['Rakefile', 'README.md']
excerpt_separator: '' # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed